# Generated by Django 4.2.2 on 2023-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.EmailField(default='xxx', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
