# Generated by Django 4.2.2 on 2023-06-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('name', models.CharField(default='Toyota', max_length=100, primary_key=True, serialize=False)),
                ('hq', models.CharField(default='Monaco, Cameroun', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Diesel', 'Diesel'), ('Fioul', 'Fioul'), ('Essence', 'Essence')], default=('Diesel', 'Diesel'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('typeName', models.CharField(default='New model', max_length=100, primary_key=True, serialize=False)),
                ('nbSeats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(default='explosion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(choices=[('Continue', 'Continue'), ('Alternative', 'Alternative')], default=('Continue', 'Continue'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(choices=[('Constant', 'Constant'), ('Variable', 'Variable')], default=('Constant', 'Constant'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbHorses', models.IntegerField()),
                ('carburant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.carburant')),
                ('enginetype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.enginetype')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.powertype')),
                ('speed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.speedtype')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(default='new model', max_length=200)),
                ('color', models.CharField(default='No color provided', max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('state', models.IntegerField()),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.builder')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.cartype')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.cars')),
            ],
        ),
    ]
