# Generated by Django 4.2.2 on 2023-06-23 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('name', models.CharField(default='Toyota', max_length=100, primary_key=True, serialize=False)),
                ('hq', models.CharField(default='Monaco, Cameroun', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Diesel', 'Diesel'), ('Fioul', 'Fioul'), ('Essence', 'Essence')], default=('Diesel', 'Diesel'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('type_name', models.CharField(default='Regular', max_length=100, primary_key=True, serialize=False)),
                ('nb_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Combustion', 'Combustion'), ('Explosion', 'Explosion'), ('Electrique', 'Electrique')], default='Explosion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Continue', 'Continue'), ('Alternative', 'Alternative')], default=('Continue', 'Continue'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Constant', 'Constant'), ('Variable', 'Variable')], default=('Constant', 'Constant'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('price', models.FloatField()),
                ('description', models.TextField(default='No description provided.')),
                ('model', models.CharField(default='new model', max_length=200)),
                ('color', models.CharField(default='No color provided', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('state', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('nb_horses', models.IntegerField(default=0)),
                ('builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.builder')),
                ('car_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.cartype')),
                ('carburant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.carburant')),
                ('engine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.enginetype')),
                ('power', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.powertype')),
                ('speed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.speedtype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
