# Generated by Django 4.2.2 on 2023-06-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carModel',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='cartype',
            old_name='typeName',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='enginetype',
            new_name='engine_type',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='nbHorses',
            new_name='nb_horses',
        ),
        migrations.RenameField(
            model_name='enginetype',
            old_name='typeName',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='powertype',
            old_name='typeName',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='speedtype',
            old_name='typeName',
            new_name='type_name',
        ),
    ]
