# Generated by Django 4.2.2 on 2023-06-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_rename_carmodel_car_car_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='car_type',
        ),
    ]
