# Generated by Django 4.2.2 on 2023-06-22 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_rename_type_car_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visitor.engine'),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='type_name',
            field=models.CharField(choices=[('Combustion', 'Combustion'), ('Explosion', 'Explosino'), ('Electric', 'Electric')], default='Explosion', max_length=200),
        ),
    ]
