# Generated by Django 4.2.2 on 2023-06-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_car_engine_alter_enginetype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='type_name',
            field=models.CharField(default='Regular', max_length=100, primary_key=True, serialize=False),
        ),
    ]
