# Generated by Django 4.2.2 on 2023-06-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_cartype_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartype',
            old_name='nbSeats',
            new_name='nb_seats',
        ),
    ]
