# Generated by Django 4.2.2 on 2023-06-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_remove_engine_carburant_remove_engine_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginetype',
            name='type_name',
            field=models.CharField(choices=[('Combustion', 'Combustion'), ('Explosion', 'Explosion'), ('Electrique', 'Electrique')], default='Explosion', max_length=200),
        ),
    ]
